<?php
    require_once './app/views/layout/header.phtml';
?>


<div class="container-sm mt-5">
    <h2 class="fs-3 fw-bold mt-5 mb-3">Agregar Opinion</h2>
    <form class="mb-5" action="addOpinion" method="POST">
        <div class="mb-3">
            <label for="dni" class="form-label">Dni</label>
            <input type="text" class="form-control" name="dni" id="dni" required>
        </div>
        <div class="mb-3">
            <label for="fecha" class="form-label">Fecha</label>
            <input class="form-control" type="date" name="fecha" id="fecha" required></input>
        </div>
        <div class="mb-3">
            <label class="form-label">Imagen</label>
            <select class="form-select mb-3" aria-label="Default select example" name="reputacion" required>;
                <option value="" selected disabled>Seleccione imagen</option>;
                <option value="Positiva">Positiva</option>
                <option value="Positiva">Negativa</option>
            </select>
        </div>
        <div class="mb-3">
            <label class="form-label">Profesor</label>
            <select class="form-select mb-3" aria-label="Default select example" name="id_profesor" required>
                <?php foreach ($profesores as $profesor): ?>
                    <option value="<?= $profesor->id?>"><?= $profesor->nombre ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Insertar</button>
    </form>
</div>

