<?php       
    require_once 'app/models/opinion.model.php';
    require_once 'app/controllers/opinion.controller.php';

    class OpinionView {

        public function showOpiniones($opiniones, $profesores) {
            require_once 'app/views/form.alta.phtml';
            echo '<table class="table container-sm">
                    <thead>
                    <tr>
                        <th scope="col">#Dni</th>
                        <th scope="col">#Fecha</th>
                        <th scope="col">Reputacion</th>
                        <th scope="col">Profesor</th>
                    </tr>
                    </thead>
                <tbody>';
            foreach($opiniones as $opinion){
                $nombreProfesor = null;
                foreach ($profesores as $profesor) {
                    if ($profesor->id == $opinion->id_profesor) {
                        $nombreProfesor = $profesor->nombre;
                        break;
                    }
                }
                echo '<tr>
                        <td>' . $opinion -> dni . '</td>
                        <td>' . $opinion -> fecha . '</td>
                        <td>' . $opinion -> reputacion . '</td>
                        <td>' . $nombreProfesor . '</td>
                    </tr>';
                }
                echo '</tbody>
                </table>';
        }

    }